In [2]:
import numpy as np
import pandas as pd

In [41]:
with open('pali.txt') as f:
    list_words = f.readline().strip().split(',')
    k = [i for i in list_words if i.lower()==i[::-1].lower()]
    k.sort()
    print(k,len(k))

['civic', 'dad', 'degged', 'detartrated', 'dewed', 'eve', 'evitative', 'kayak', 'level', 'madam', 'malayalam', 'mom', 'noon', 'racecar', 'radar', 'redder', 'refer', 'revver', 'rotator', 'rotor', 'sagas', 'selles', 'solos', 'stats', 'tattarrattat', 'tenet', 'wow'] 27


In [25]:
conda install ipykernels
ipython kernel install --user --name officehour-python3.8


SyntaxError: invalid syntax (<ipython-input-25-5c523cfe3bbe>, line 1)

In [26]:
class d:
    def __init__(self,p,q):
        self.p = p
        self.q = q
        self.params = {'a':1}

class a(d):
    def k(self):
        for i in self.params.items():
            print(i)
l = a(2,32)
l.k()

('a', 1)


In [45]:
sigmoid = lambda f: 1/(1+np.exp(-f))
sigmoid(np.array([2,3]))

array([0.88079708, 0.95257413])

In [18]:
b = np.array([[2,4],[3,3],[9,1]])
a = np.array([[4],[5],[6]]).reshape(-1,1)
b.shape
np.array([1,2]).shape

(2,)

In [17]:
a = np.array([[4],[5],[6]])
print(a.shape)
b = np.array([[2],[3],[9]]).reshape(-1,1)
print(np.array([[1,2]]).shape)
l = a + np.array([[1,2]])
print(np.array([[3,4],[3]]).shape)
print(l.shape)
l

(3, 1)
(1, 2)
(2,)
(3, 2)


array([[5, 6],
       [6, 7],
       [7, 8]])

In [40]:
np.ones((10,2)) + np.array([3,4])

array([[4., 5.],
       [4., 5.],
       [4., 5.],
       [4., 5.],
       [4., 5.],
       [4., 5.],
       [4., 5.],
       [4., 5.],
       [4., 5.],
       [4., 5.]])

# a = []
k = a.copy()
print(id(a), id(k))

In [18]:
k = []
k.append(np.random.rand(2,1))
for i in k:
    print(i)
    print(i[1][0])
    

[[0.08534226]
 [0.88034565]]
0.8803456509384785


In [39]:
a = 5
print(1) if a>2 else 3

1


In [42]:
for i in range(4):
    if i==3:
        print(4)
        continue
else:
    print(10)

4
10
